### ISSUE TITLE
No informa correctamente cuando esta trabajando, dando la sensación de estar colgado

### ISSUE THREAD

**Issue by sergutsan** [javierriveracastro/descargador#1]
El diálogo de grabación del fichero LaTeX se queda colgado en mi máquina y tengo que cancelar con Ctrl-C. No tengo claro por qué, pero pongo aquí algunas trazas de excepciones que me aparecen en la pantalla por si ayudan. 

Esto es lo que sale si digo "Grabar" y luego cancelo (el programa no se cuelga en este caso, pero igual estos errores dan pistas sobre lo que ocurre): 

[ < UmbriaDescargar.Umbria.Escena object at 0xae57332c > ]

(python:27505): GLib-CRITICAL **: Source ID 1972 was not found when attempting to remove it

(python:27505): GLib-CRITICAL **: Source ID 1988 was not found when attempting to remove it

(python:27505): GLib-CRITICAL **: Source ID 2009 was not found when attempting to remove it

(python:27505): GLib-CRITICAL **: Source ID 2026 was not found when attempting to remove it

(python:27505): GLib-CRITICAL **: Source ID 2047 was not found when attempting to remove it

y esto es lo que sale si intento dar un nombre de fichero y grabar: 

^CTraceback (most recent call last):
  File "Descargador.py", line 75, in genera_pdf
    GeneradorText(nome_dir, self.partida)
  File "/tmp/descargador/trunk/UmbriaDescargar/UmbriaTex.py", line 55, in **init**
    fichero.write(self.genera_escena(escena))
  File "/tmp/descargador/trunk/UmbriaDescargar/UmbriaTex.py", line 134, in genera_escena
    for post in escena.posts():
  File "/tmp/descargador/trunk/UmbriaDescargar/Umbria.py", line 135, in posts
    self.url, pagina_siguiente))
  File "/tmp/descargador/trunk/UmbriaDescargar/Umbria.py", line 214, in leer_pagina
    return self.opener.open(direccion, None, HTTP_TIMEOUT).read()
  File "/usr/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 543, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 585, in _read_chunked
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt

HTH

**Comment by javierriveracastro** [comment]
¿No sera simplemente que no da ningún tipo de feedback (eso creo que esta en un TODO por ahí adelante) y no le das tiempo a descargar todo?.

El error de glib no debería tener importancia, y cuando das a CTRL+C se corta esperando una respuesta de la red.

Lo que te pide el dialogo es un directorio para grabar el tex y todas las imágenes que necesite (que son muchas para una partida entera), no le des el home o algo así que te lo llena de m....

Si puedes prueba con una escena pequeña primero.

**Comment by sergutsan** [comment]
OK, eso explica lo que observo. Debería haberme fijado en que la tarjeta de red estaba a tope mientras estaba "colgado". 

Asunto resuelto, entonces.

**Comment by javierriveracastro** [comment]
Nops, es claramente un bug.
